version: '3.9'

networks:
  back:

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
      target: php
    working_dir: /app
    depends_on:
      - postgres
    environment:
      - APP_KEY=${APP_KEY}
    volumes:
      - ./src:/app
    #      - ./.env:/app/.env
    networks:
      - back
    ports:
      - "7474:8000"


  #  schedule:
  #    build:
  #      context: .
  #      dockerfile: /docker/dockerfile
  #      target: cron
  #    depends_on:
  #      - postgres
  #    networks:
  #      - back

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - back
    ports:
      - "4545:5432"