version: '3.9'

networks:
  back:

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
      target: build
    working_dir: /app
    depends_on:
      - postgres
    environment:
      - APP_KEY=${APP_KEY}
    networks:
      - back
    ports:
      - "7474:8000"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - back
    ports:
      - "4545:5432"